#!/usr/bin env Rscript
args <- commandArgs(TRUE)
n<-length(args)
if (n!=3) stop("\nusage: <infile> <sample_name> <outfile>\n")
bitmap(file=args[3],width =14,height =12,type = "png16")
par(ann=F,mar=c(6,5,5,4),xpd=TRUE)
a <- read.delim(args[1],header=FALSE)
name <- paste("Cumulative depth distribution of sample",args[2])
plot(x=a[,1],y=a[,3],type ="l",col ="red",lwd=2)
title(main=name,font.main=2,font=10)
title(xlab="Cumulative sequencing depth",ylab="Fraction of target bases",font.lab=2,font=6)
box()
