#! /usr/bin/perl -w

use strict;
use File::Path;
use File::Basename;
use Getvar.pl -format vcf4 --includeinfo $indel_dir/$sample.somaticindel.vcf >$indel_dir/$sample.sindel.annovar && \\\n"; ##20160107 sindel.vcf->somaticindel.vcf
        $content .= "perl $annodir/summarize_annovar.pl --buildver hg19 --verdbsnp 137 $indel_dir/$sample.sindel.annovar $annodir && \\\n";
        $content .= "perl $Bin/bin/csv2report.pl $indel_dir/$sample.sindel.annovar.exome_summary.csv $indel_dir && \\\n";
        $content .= "rm -f $indel_dir/$sample.sindel.annovar.*ed";
        &generateShell($shell,$content);
        return $shell;
}
